#:schema node_modules/wrangler/config-schema.json
name = "prisma-driver-adapters-nuxt"
compatibility_date = "2024-04-05"

[[d1_databases]]
binding = "D1_DATABASE" # i.e. available in your Worker on env.D1_DATABASE
database_name = "d1-cfpages-nuxt"
database_id = "d3d2e616-a7f8-4511-830f-dcda5e4ee4c4"
