#:schema node_modules/wrangler/config-schema.json
name = "prisma-driver-adapters-vitest"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "D1_DATABASE" # i.e. available in your Worker on env.D1_DATABASE
database_name = "d1-vitest"
database_id = "a08bdee3-ff5f-4227-848c-ab7ec15cf991"
