name = "e2e-cloudflare-workers"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-09-28"
webpack_config = "webpack.config.js"

[vars]
