name = "e2e-cloudflare-workers"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-09-28"
webpack_config = "webpack.config.js"

[vars]
CF_DATA_PROXY_URL="prisma://aws-us-east-1.prisma-data.com/?api_key=E-9HAnjYDhBWd3vcNjo0Z1fVtirpfR140rct4G65Tf8E4ELFEnRwsgXXK0bpm37M"
