# Docs https://developers.cloudflare.com/workers/wrangler/configuration/

name = "e2e-cloudflare-workers-module"
main = "./src/index.ts"
compatibility_flags = []
workers_dev = true

# Note: prepare.sh will append the CLOUDFLARE_DATA_PROXY_URL at the end
[vars]
