# Docs https://developers.cloudflare.com/workers/wrangler/configuration/

name = "e2e-cloudflare-workers"
main = "./src/index.ts"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-05-03"
