# Docs https://developers.cloudflare.com/workers/wrangler/configuration/

name = "e2e-cloudflare-workers"
type = "webpack"
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-05-03"
webpack_config = "webpack.config.js"

[vars]
