service: e2e-tests-platforms-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 10
  versionFunctions: false
  tracing:
    lambda: true

functions:
  hello:
    handler: index.handler
    name: e2e-tests-platforms-serverless-lambda
    environment:
      SERVERLESS_LAMBDA_PG_URL: ${env:SERVERLESS_LAMBDA_PG_URL}
