name = "pg-cfpages-basic"
main = "src/index.js"
compatibility_date = "2023-10-30"
node_compat = true

# Note: prepare.sh will append the env vars at the end
[vars]
DATABASE_URL="postgresl://foo:5432/bar?schema=lala"
