service: e2e-tests-serverless-lambda-npm

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 10
  versionFunctions: false
  tracing:
    lambda: true

functions:
  hello:
    handler: index.handler
    name: e2e-tests-serverless-lambda-npm
    environment:
      DATABASE_URL: ${env:DATABASE_URL}

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/query-engine-*'
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node'
    - 'node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'
