name: check-for-update
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: check-for-update
        run: sh check-for-update.sh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
