name: check-for-update
on:
  # Manual UI in GitHub https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
  schedule:
    # Run every five minutes
    - cron: '*/5 * * * *'

env:
  PRISMA_TELEMETRY_INFORMATION: 'e2e-tests check-for-update.yaml'
jobs:
  check-for-latest-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: use node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: check latest update
        run: bash .github/scripts/check-for-update.sh latest
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-dev-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: use node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: check dev update
        run: bash .github/scripts/check-for-update.sh dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-patch-dev-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: use node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: check patch-dev update
        run: bash .github/scripts/check-for-update.sh patch-dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-integration-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: use node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: check integration update
        run: bash .github/scripts/check-for-update.sh integration
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  report-to-slack-failure:
    runs-on: ubuntu-latest
    needs:
      - check-for-latest-update
      - check-for-dev-update
      - check-for-patch-dev-update
    if: failure()
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: report failure to slack
        run: bash .github/scripts/slack-workflow-status.sh "check-for-update :x:"
        env:
          SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_WORKFLOWS }}
