name: invoke-platforms-lambda-function
on:
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: platforms/lambda

    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE: ${{ secrets.AWS_ROLE }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - run: yarn ts-node test.ts
