name: lint pr
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  enforce-semantic-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
