name: test

on:
  push:
    paths-ignore:
      - '*.md'
      - 'renovate.json'

jobs:

  os:
    strategy:
      fail-fast: false
      matrix:
        engine: ['napi', 'binary']
        os: [ubuntu-latest, m1]
        node: [14] #[12,14,15,16]
    runs-on: ${{ matrix.os }}

    env:
      OS_BASE_PG_URL: ${{ secrets.OS_BASE_PG_URL }}

    steps:
      - uses: actions/checkout@v2

      - name: Define Engine Type to test
        if: ${{ matrix.engine == 'napi' }}
        run: echo "PRISMA_FORCE_NAPI=true" >> $GITHUB_ENV

      - name: Install Dependencies
        run: yarn install

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: node ./generic/basic/m1.js
      - run: arch -arm64e node ./generic/basic/m1.js

      - name: test on ${{ matrix.os }} - ${{matrix.engine}}
        run: bash .github/scripts/test-project.sh generic basic ${{ matrix.os }}
        if: ${{ matrix.os != 'm1' }}

      - name: test on ${{ matrix.os }} - ${{matrix.engine}} (force run as arm64)
        run: arch -arm64 bash .github/scripts/test-project.sh generic basic ${{ matrix.os }}
        if: ${{ matrix.os == 'm1' }}
