name: test

on:
  # Note about push & pull_request
  # when creating a new branch for a PR, push will be triggered immediately before the PR gets created
  # The GitHub API / GitHub context base commit is then 0000000000000000000000000000000000000000
  #
  # The get-changed-files action used in the detect_jobs_to_run needs to have a non 0 base commit to ba able to diff
  # Defining both push (and specify the branches) and pull_request solves the problem
  push:
    branches:
      # Push events our default branch
      - dev
      # Push events on our special branches
      - patch-dev
      - latest
      - integration
  pull_request:
    paths-ignore:
      - '*.md'
      - 'renovate.json'

env:
  PRISMA_TELEMETRY_INFORMATION: 'ecosystem-tests test.yaml'
  CI: 1
  SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_WORKFLOWS }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
  DATABASE_URL_POSTGRES_TEMPLATE: ${{ secrets.DATABASE_URL_POSTGRES_TEMPLATE }}

defaults:
  run:
    # this makes windows use bash as well, which makes `...  >> $GITHUB_ENV` work there
    shell: bash

jobs:
  openssl:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        clientEngine: ['library', 'binary']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Define Client Engine Type to test
        run: echo "PRISMA_CLIENT_ENGINE_TYPE=${{ matrix.clientEngine }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Set test specific DATABASE_URL
        run: |
          string=${{ env.DATABASE_URL_POSTGRES_TEMPLATE }}
          search=database
          replace=${{ github.job }}_${{ matrix.os }}_${{ matrix.clientEngine }}
          replaced=${string/$search/$replace}
          echo "DATABASE_URL=$replaced" >> $GITHUB_ENV

      - name: test on ${{ matrix.os }} - ${{ matrix.clientEngine }}
        id: run-test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh generic basic ${{ matrix.os }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh generic basic ${{ matrix.os }}
