name: test

on:
  push:
    paths-ignore:
      - '*.md'
      - 'renovate.json'

jobs:

  platforms:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        engine: ['binary'] # see extracted napi below
        platform:
          - heroku
          - aws-graviton
          - codesandbox
          - m1-macstadium
        os: [ubuntu-latest] #, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    concurrency: ${{ github.run_id }}-platforms-${{ matrix.platform }}

    env:
      START_TIME: ${{ needs.start-time.outputs.start-time }}
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      HEROKU_PG_URL: ${{ secrets.HEROKU_PG_URL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      SSH_KEY_GRAVITON: ${{ secrets.SSH_KEY_GRAVITON }}
      SSH_KEY_M1_MACSTADIUM: ${{ secrets.SSH_KEY_M1_MACSTADIUM }}

    steps:
      - uses: actions/checkout@v2

      - name: use node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn

      # Install Puppeteer for Codesandbox test only
      - name: Install Puppeteer
        if: ${{ matrix.platform == 'codesandbox' }}
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: yarn --ignore-engines

      - name: test ${{ matrix.platform }} - binary
        id: run-test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: bash .github/scripts/test-project.sh platforms ${{ matrix.platform }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh platforms ${{ matrix.platform }}

  platforms-napi:
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        platform:
          - heroku
          - aws-graviton
          - codesandbox
          - m1-macstadium
        os: [ubuntu-latest] #, windows-latest, macos-latest]
        exclude:
          - platform: heroku # https://github.com/prisma/e2e-tests/issues/1748
    runs-on: ${{ matrix.os }}
    concurrency: ${{ github.run_id }}-platforms-${{ matrix.platform }}
    env:
      START_TIME: ${{ needs.start-time.outputs.start-time }}
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      HEROKU_PG_URL: ${{ secrets.HEROKU_PG_URL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      SSH_KEY_GRAVITON: ${{ secrets.SSH_KEY_GRAVITON }}
      SSH_KEY_M1_MACSTADIUM: ${{ secrets.SSH_KEY_M1_MACSTADIUM }}
      PRISMA_FORCE_NAPI: true

    steps:
      - uses: actions/checkout@v2

      - name: use node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn

      # Install Puppeteer for Codesandbox test only
      - name: Install Puppeteer
        if: ${{ matrix.platform == 'codesandbox' }}
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: yarn --ignore-engines

      - name: test ${{ matrix.platform }} - napi
        id: run-test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: bash .github/scripts/test-project.sh platforms ${{ matrix.platform }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh platforms ${{ matrix.platform }}