name: upgrade-branch-to-version
on:
  # Manual UI in GitHub https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
    inputs:
      branch:
        description: Which branch to upgrade? (Attention, has to reflect Npm dist tag as well!) TODO
        default: 'dev'
        required: true
      prismaVersion:
        description: What version of Prisma to upgrade to? (Not used yet!) TODO
        default: 
        required: true

env:
  PRISMA_TELEMETRY_INFORMATION: 'ecosystem-tests upgrade-branch-to-version.yaml'

jobs:
  upgrade-branch-to-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: use node 12
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: upgrade-branch-to-version.sh
        run: bash .github/scripts/upgrade-branch-to-version.sh ${{github.event.inputs.branch}} ${{github.event.inputs.prismaVersion}}
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  report-to-slack-failure:
    runs-on: ubuntu-latest
    needs:
      - upgrade-branch-to-version
    if: failure()
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: report failure to slack
        run: echo "disabled"
        # TODO run: bash .github/scripts/slack-workflow-status.sh "check-for-update :x:"
        env:
          SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_WORKFLOWS }}
