# Docs https://developers.cloudflare.com/workers/wrangler/configuration/

name = "e2e-cloudflare-workers-module-auto-import-custom-output"
main = "./src/index.ts"
compatibility_flags = []
workers_dev = true
compatibility_date = "2023-06-02"

# Note: prepare.sh will append the DATAPROXY_COMMON_URL at the end
[vars]
